name: flutter_google_places_sdk_platform_interface
description: A common platform interface for accessing google maps native sdk on various platforms
version: 0.1.0+2
author: Matan Shukry
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk_platform_interface

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.9

flutter:
  assets:
    - assets/google/
